name: protein_mpnn
channels:
  - defaults
  - conda-forge
  - pytorch
  - dglteam
  - nvidia
dependencies:
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio
  - pandas
  - pytorch
  - torchaudio
  - torchdata
  - torchvision
  - dgl
  - pip
  - pip:
    - -e .
