[build-system]
requires = [
    "setuptools >= 61.0",
    "setuptools-scm>=8.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "protein_mpnn"
description = "ProteinMPNN is a deep learning based protein sequence design software"
readme = "README.md"
urls = { Homepage = "https://github.com/dauparas/ProteinMPNN" }
license = { file = "LICENSE" }

requires-python = ">=3.9"
dynamic = ["version"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Programming Language :: Python :: 3",
]
dependencies = [ "pytorch >= 1.9" ]

[project.scripts]
protein_mpnn = "protein_mpnn:main"

[tool.setuptools.package-data]

[tool.setuptools_scm]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.ruff]
line-length = 100
